/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 30-srp-2018 16:33:40 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */

DROP TABLE IF EXISTS `TABLE_A` CASCADE
;

DROP TABLE IF EXISTS `TABLE_B` CASCADE
;

DROP TABLE IF EXISTS `TABLE_C` CASCADE
;

/* Create Tables */

CREATE TABLE `TABLE_A`
(
	`ID` INT NOT NULL,
	`COLUMN_A` INT NULL,
	`COLUMN B` INT NULL,
	CONSTRAINT `PK_Table A` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `TABLE_B`
(
	`COLUMN_A` INT NULL,
	`COLUMN B` INT NULL
)

;

CREATE TABLE `TABLE_C`
(
	`COLUMN_A` INT NULL,
	`COLUMN B` INT NULL
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `TABLE_B`
 ADD CONSTRAINT `FK_TABLE_B_TABLE_A`
	FOREIGN KEY (`COLUMN_A`) REFERENCES `TABLE_A` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `TABLE_C`
 ADD CONSTRAINT `FK_TABLE_C_TABLE_A`
	FOREIGN KEY (`COLUMN_A`) REFERENCES `TABLE_A` (`ID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
;
